name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Build and Deploy
          uses: actions/setup-node@master
#           uses: actions/github-pages-deploy-action@master
          env:
            ACCESS_TOKEN: $
            BRANCH: master
            FOLDER: dist/bundle.js
            BUILD_SCRIPT: npm install && npm run build
