on: [deployment]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: deploy-pages@homework3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
        
